### ISSUE TITLE
So when do you think you'll be able to enable session choosing?

### ISSUE THREAD

**Issue by SolarAquarion** [Obsidian-StudiosInc/entrance#12]

**Comment by wltjr** [comment]
What do you mean by session choosing? Wayland vs X? Or something else?

**Comment by SolarAquarion** [comment]
the parsing of /usr/share/xsessions

**Comment by SolarAquarion** [comment]
also /usr/share/wayland-sessions

**Comment by wltjr** [comment]
I think I need to add that back or something. I removed it in commit b9210fc not sure if it was needed or not. It may not be needed as its own file but likely need to use system provided or something.

**Comment by SolarAquarion** [comment]
@wltjr so the session choosing is supposed to from a drop down or similar, where you can choose your wayland session or xsession as existing in your system.  It's a series of desktop files.  

Sourcing the /etc/profile, /etc/profile.d, ~/.prfofile, and ~/.xprofile and other other such files are a good idea

**Comment by SolarAquarion** [comment]
https://github.com/GNOME/gdm/blob/master/data/Xsession.in

gdm has something

**Comment by wltjr** [comment]
I haven't anything for Wayland yet, so its bound to X sessions for now. There is a select box on the right next to login button that allows you to choose the session. I have only tested E and EPYMC, but you should be able to log into other desktop sessions, like XFCE. Not sure about Gnome or KDE, may need to support logind/elogind.

I have been stuck in Java world packaging stuff to free myself of Gentoo's Java packages and tree. Its a crufty mess. I already did the same for all EFL/E stuff a bit ago. Much less of that, so easier to wrangle into better condition than the tons of Java stuff... Once done will get back to logind/elogind support in entrance and other stuff.

**Comment by wltjr** [comment]
I could see about adding Wayland sessions to the X sessions. But I do not believe it will launch a Wayland session without logind/elogind, need seat support etc to pass to Wayland. Just the same need to figure out X cookie or what ever from logind/elogind. To replace consolekit. Though read something that they can be used together. Not sure how I will handle that stuff just yet. Not sure how other DM are handling the X or Wayland session. Are they in the same drop down just marked differently? I played around with launching KDE under wayland via SDDM but never had any luck. Same with E but I guess I wasn't running logind/elogind or something.

**Comment by SolarAquarion** [comment]
gdm and lightdm are the ones that are most likely to work

**Comment by wltjr** [comment]
Do they have a single list and just mark x and wayland? I used to use lightdm for a bit but never saw it having any options.E does not provide a wayland session file. I know it has a [X session file](https://github.com/Enlightenment/enlightenment/blob/master/data/session/enlightenment.desktop.in). I guess they use the same for both X and Wayland. But like you mentioned from what I have read they go in different locations in /usr/share. Not like EFL/E devs care how people log into E. Given they abandoned entrance and pretty much everyone logs in differently. Some use lightdm, some spawny, some spawny + anna, some run startx, etc. Not to surprised no wayland desktop file. Or if the same one gets installed in 2 locations.

**Comment by SolarAquarion** [comment]
For now just do /usr/share/xsessons/ Later once you do all the logind stuff and related do wayland-sessions

**Comment by wltjr** [comment]
It should already do /usr/share/xessions. Is the drop down on the left of the login button not working? It is a hoverselect/dropdown or popup. I can use that to log into E or EPYMC, though not a regular X session.

**Comment by wltjr** [comment]
Maybe a bug, I think its based on install location or something. It is not to looking in /usr/share/xessions explicitly. It is based on the [install path](https://github.com/Obsidian-StudiosInc/entrance/blob/master/src/daemon/entrance_session.c#L455) I think. Maybe a bug as it likely should have /usr/share/xessions like /etc, etc. Even if a user puts it some where else. I may need to add another option in there.

**Comment by wltjr** [comment]
I think those etc locations are legacy and its been /usr/share/xesssions for some time. Not sure I need to keep those others anymore. Maybe just /usr/share/xesssion and the current for if a user installs it some where else and there is a xession folder, etc.

**Comment by SolarAquarion** [comment]
The sourcing of /etc/profile.d and such are still good ideas

**Comment by wltjr** [comment]
Not sure about for sessions, that maybe a new location. I was talking about these
```
   /* Maybee need to scan other directories ? */
   _entrance_session_desktops_scan("/etc/share/xsessions");
   _entrance_session_desktops_scan("/etc/X11/dm/Sessions");
snprintf(buf, sizeof(buf), "%s/xsessions", efreet_data_home_get());
```
Nice typo in comment, shows how much attention the author was paying when first coding. The whole codebase is a horrible mess. How other EFL devs spoke of the original author was not encouraging and explains many issues in EFL/E.... They started a new module for network manager, oconnection, using the old api for gadgets. Which is still more stable, but anything new should support new API and old if not just new. Like all the bryce stuff uses new API. Shelf stuff uses old.

**Comment by wltjr** [comment]
I bet in your case efreet_data_home_get is not returning /usr/share.

**Comment by SolarAquarion** [comment]
Yeah /etc/share is trash

**Comment by SolarAquarion** [comment]
/etc/X11/xdm is not needed

**Comment by wltjr** [comment]
I think so is /etc/x11/dm, legacy cruft if it was ever used... I think I will drop both those for /usr/share/xsession or something. Slowly having to recode the entire think. Still a bit better than starting from scratch, but I can see why others including the author walked away from the codebase... None the less I will get it into shape in 2018 :)

**Comment by SolarAquarion** [comment]
there's /etc/X11/Sessions, but only fvwm-crystal uses that.  I removed that

**Comment by SolarAquarion** [comment]
https://www.archlinux.org/packages/extra/any/fvwm-crystal/ look at the file list

**Comment by wltjr** [comment]
Its odd upstream has no official documents on such, like mentioned in the following links. Seems lightdm is a freedesktop.org project or something. It mentions /usr/share/xession.
https://www.freedesktop.org/wiki/Software/LightDM/CommonConfiguration/
https://www.freedesktop.org/wiki/Software/LightDM/Design/

A bug makes the /etc/X11/sessions. Its odd
https://bugs.freedesktop.org/show_bug.cgi?id=89285

Anyway I will look into this time permitting. Likely see about a hard coded /usr/share or something. In case efreet is else where.

**Comment by SolarAquarion** [comment]
that's how most of them do it I think

**Comment by wltjr** [comment]
Freedesktop.org should have some spec on it to be standard. Otherwise each has to look to the other and it becomes a mess which we have :)

**Comment by SolarAquarion** [comment]
Yeah, there's probably a spec for it

**Comment by SolarAquarion** [comment]
data/man/sddm.conf.rst.in:      Default value is "/usr/share/xsessions".
docs/THEMING.md:**sessionModel:** This is a list model which contains information about the desktop sessions i
src/common/Configuration.h:            Entry(SessionDir,          QString,     _S("/usr/share/xsessions"),

 data/man/sddm.conf.rst.in:      Default value is "/usr/share/wayland-sessions".
src/common/Configuration.h:            Entry(SessionDir,          QString,     _S("/usr/share/wayland-sessions

data/lightdm.conf:#sessions-directory=/usr/share/lightdm/sessions:/usr/share/xsessions:/usr/share/wayland-sess

**Comment by SolarAquarion** [comment]
Each display manager re-implements it

**Comment by wltjr** [comment]
Yeah I could not find any common spec. I have seen the /usr/share/wayland-sessions in some docs somewhere before. I thought that was standard location for at least wayland...

**Comment by SolarAquarion** [comment]
Basically you'll just need to do it yourself

**Comment by wltjr** [comment]
Yeah I get that, just ridiculous no standardization here... I guess explains some what the various paths in entrance now. Not sure why its so hard to come up with some standard there... Oh well I will just add in /usr/share/xsession and /usr/share/wayland-session. Just need to see if it duplicates stuff from the path using efreet path. May have to drop that. I am not sure anyone will ever use that, have some xesssion directory in some other layout with efreet also using that, a location other than /usr/share. I do not see that being the case. Though maybe what you have now if the session files are not showing up.

**Comment by wltjr** [comment]
That should address the issue for now. Wayland sessions will show up but likely not work till entrance has logind/elogind support. Probably should have left it out for now, but its there :P I will see about doing a new release in the next week or so. Need to tweak the date alignment last month and this was off to the right a bit. Also change up the effects a bit.

**Comment by SolarAquarion** [comment]
oh /etc/profile.d and other such file should be sourced on logon

**Comment by wltjr** [comment]
Have to see what they are doing there. Do they not have a xdm? That is not the old actual XDM, though it may also come with that. Usually its just a wrapper. Think arch tends to be pretty close to Gentoo in that regard. They must be doing something different.

How are you starting entrance? init.d script or systemd?

**Comment by SolarAquarion** [comment]
systemd

**Comment by wltjr** [comment]
Looks like arch does things pretty differently. I will have to come up with something for that. Maybe more something for systemd. Seems systemd is preferred on arch. I guess it does not provide means for such. Seems to use [one for each DM](https://wiki.archlinux.org/index.php/Xprofile)

"Most display managers source /etc/xprofile, ~/.xprofile and /etc/X11/xinit/xinitrc.d/. For more details, see xprofile."
https://wiki.archlinux.org/index.php/Display_manager#Autostarting

Its a pretty strange distro. They leave way to much up to the user to do and each DM has its own Xsession file vs a more universal one. Plus the choice on starx, xinit, xdm, and slim.

Anyway I will look into it and see what I can come up with. May have to restore that old file and install it when logind option is enabled along with the systemd file. Have to see how the other DMs are loading the Xsessions file. If they are doing it via code or some wrapper script. I could likely put a wrapper script in place of the ```ExecStart=/path/entrance --nodaemon``` So the Xsession wrapper script is called then it invokes entrance.

**Comment by wltjr** [comment]
I guess each Xsession file for each DM sources /etc/profile.d, or some profile file that does that. Does your /etc/profile have a line on sourcing /etc/profile.d? Or is that left up to the DM? I am assuming its left up to the DM.

**Comment by SolarAquarion** [comment]
Yes just look at lightdm.conf

**Comment by SolarAquarion** [comment]
Or similar

**Comment by SolarAquarion** [comment]
https://git.archlinux.org/svntogit/packages.git/tree/trunk/Xsession?h=packages/lightdm

gdm has one
https://github.com/GNOME/gdm/blob/master/data/Xsession.in

**Comment by wltjr** [comment]
Its pretty universal. Why Gentoo has a wrapper. Arch seems to go with the one provided from each. Likely due to a lack of man power or something. I much prefer general universal things vs application specific and duplicating the same basic function. Like a general arch Xsession or startDM.sh vs one for each DM.

The GDM one also does not source /etc/profile.d, so that must be done by /etc/profile or other. The lightdm one looks damn near identical to the one I removed from entrance.
Look at these two, they are pretty close
https://git.archlinux.org/svntogit/packages.git/tree/trunk/Xsession?h=packages/lightdm
https://github.com/Obsidian-StudiosInc/entrance/blob/87cbb9c32a91e519e5466882cb48e69fa144b457/data/Xsession

The gnome one is more modified but has some similar bits. That is something Arch really should be provided for ALL DMs like on Gentoo. Vs having each DM ship their own. Just how they do things on Arch. It is not as friendly to users or developers, both has to do more work it seems.

I can restore that file and have it installed for systemd, or distros that lack its own wrapper. I removed it as it was not used/needed on Gentoo. Seems it may still be on other distros or OS.

**Comment by wltjr** [comment]
I would bet the original entrance/elsa author copied a Xsession file from lightdm or something for entrance, given how close the code in each.

**Comment by SolarAquarion** [comment]
Yeah /etc/profile sources /etc/profile.d

https://git.archlinux.org/svntogit/packages.git/tree/

**Comment by wltjr** [comment]
To take a parting jab at systemd, seems with all that standardization. Nothing was done to standardize X sessions or oven profile aspect :P If anything seems the init script wrappers like Gentoo has is much better. There is 1 xdm init, so no init for sddm, lightdm, entrance, etc. Nor any Xsession files needed. It is done in a universal way for all. Such that the base system developers and xinit package manainters manage 1 file vs Xsession files x number of DMs... Nothing to do with Arch here. but systemd should have something like a xdm.service. Rather than a sddm.service, lightdm.service, entrance.service, etc. Which I bet those are all basically the same short of the executable.

Just good stuff :) More systemd, not standardizing something that badly needs it :)

**Comment by wltjr** [comment]
Ok I will restore the Xsession file and have it available for install. I guess I can install by default. I will have to experiment. I do not want to be used on Gentoo. But I could see someone maybe needing that who is not using systemd. Seems you need that on Arch regardless of using systemd or not.

I have to see what Gentoo has for xdm and systemd. If it has a wrapper like the xdm/xinit with startDM.sh or goes with the per DM service file and I guess their own Xsession. I would assume Gentoo to have a universal route for system like its openrc/xdm/xinit route.

**Comment by SolarAquarion** [comment]
there is a xdm.service but it's provided by xdm

**Comment by wltjr** [comment]
Need to shell check that file and stuff. Not to keen to having to maintain that, but seems I have no choice as some distros are leaving that up to packages themselves. You may consider filing a feature request bug with Arch. They should have a universal distro specific wrapper for any DM like Gentoo has. That seems a better approach. 1 file to maintain vs 1 for each DM.

**Comment by wltjr** [comment]
Yeah xdm on arch is completely different. On Gentoo its 2 fold, first a wrapper for all other dms. Or if you really want xdm, it will start that binary. It uses a [variable](https://github.com/gentoo/gentoo/blob/master/x11-base/xorg-server/files/xdm.confd-4#L10) in a /etc/conf.d/xdm file, and based on what you set that to, it [switches](https://github.com/gentoo/gentoo/blob/master/x11-base/xorg-server/files/xdm.initd-11#L69) through the various DMs. That way you have the same system scripts for session etc regardless of the DM. Any change is done there, vs to each DM's session file. Or the startDM.sh that is [called](https://github.com/gentoo/gentoo/blob/master/x11-base/xorg-server/files/xdm.initd-11#L180) from that init script.

The xdm init script is not even provided by xdm, but by xorg-server. xdm is the binary like entrance or other. Just uses the universal name and startup method :)

**Comment by SolarAquarion** [comment]
How would that even work it usually works like systemctl enable lightdm  -f

**Comment by wltjr** [comment]
Like Gentoo, you have some /etc/conf.d/xdm file you tell it which DM. Then you have a universal xdm.service for systemd. So that no matter what DM your using, you just edit the conf file and never touch the systemd service. You either enable it for graphical or not for non. But you do not have to switch services files to try out another DM.

Which I assume you can have more than one service enabled. Like if you enable lightdm, entrance, and sddm. Not sure if any service looks for the other and disables it. So systemd may allow you to start multiple login managers that may conflict with each other. Not sure I have no real experience with systemd. Had it on a few VMs, centos and debian, but did not play with systemd much.

**Comment by wltjr** [comment]
If the services do not disable a similar service, one login manager disables the other. Then you have 2 steps to try out another DM. You have to disable the service for one DM and then start the other. Rather than editing 1 file and just restarting the service. Which you still have to stop the dm and start the other. So you have many more steps with the systemd route enabling/disabling/stopping/starting dms.

Like stop entrance, disable service, enable lightdm, start lightdm. Vs stop xdm, edit xdm.conf, start xdm :) An extra step, but if your trying out many could eat up time. A variable you can comment out and have set to many values and switch back and forth :)

**Comment by SolarAquarion** [comment]
You can't have more then one service enabled for Display Managers, it
creates a symlink.  How does gentoo handle systemd

**Comment by wltjr** [comment]
I have no clue how Gentoo handles xdm/DMs running under systemd. I have to research that :) I have never touched systemd stuff under gentoo. Other than what I did for entrance in meson, which I never tested under Gentoo. Gentoo entrance package does not support systemd, but I guess I can add that USE flag and install the service file. I added systemd support to Tomcat, but haven't means to test 📦 

I will research how gentoo handles that. I assume it has some sort of wrappers like the xdm/startDM.sh stuff.

**Comment by wltjr** [comment]
Anyway thanks for bringing this up! I was not sure about the Xsession file when I removed it. Seems that may have been a mistake. You can grab that file for now if you want to experiment. I will see about adding it back ASAP. By the weekend at lastest.

On a mission to fully replace all needed Java packages in Gentoo's repo with ones in mine. Hundreds of packages later, I am within like 20 or so, give or take some deps of things I do not have installed. Then back onto my Java 9 fixing, and Netbeans 9 packaging. Then I can play with Java 10...

That has been sucking up all my time. Thus no more progress on say logind/elogind support, etc. Though I added in some fake/static seat0 env vars. Not sure if the env vars needed to start wayland are provided or not. I think it may have some of that, or all that is needed to start wayland even without logind/elogind. That just allows it to be dynamic, and have say seat1, 2, etc. Based on hardware vs hard coded or config file. Also need to make a UI to manage the configuration file. Along with respecting all settings. Seems several are ingnored. background did not work and I removed code there, so need to add new working code back for custom background. There is a var to set the VT, and that for sure does not work. There is no code to load that and the VT is hard coded.

Entrance codebase was and some what still is a total mess. I am not exaggerating or being critical of the developer. There were so many issues, and so much code that did not make sense, over engineered, incomplete, typos, broken, etc. I can easily see why others walked and rather start over. Though I still thing the guts can be salvaged with some major renovation :) A fixer upper :P 

Anyway thanks again for bringing up the Xsession stuff. Others may have ran into issues there and just not said anything and were unable to run or use Entrance. Not sure I would have revisited it otherwise.

**Comment by SolarAquarion** [comment]
solaraquarion@apollo   ~/habs    (git)-[ master]   sudo systemctl enable entrance -f  ✔  1288  12:41:15 
[sudo] password for solaraquarion:          
Removed /etc/systemd/system/display-manager.service.
Created symlink /etc/systemd/system/display-manager.service → /usr/lib/systemd/system/entrance.service.

**Comment by wltjr** [comment]
Per your comments Arch uses a common service name and symlinks to that. But they do not have a common Xsession startup. That seems to be left to each. I will see about addressing it this week.

**Comment by SolarAquarion** [comment]
knock knock

**Comment by wltjr** [comment]
@SolarAquarion I haven't forgot I have been busy with Java 9 stuff and Netbeans 9. I code in Netbeans so its effected my development for the past month or so. I have a binary snapshot I downloaded to do work when needed. I will see about making some time to do that. Oracle has not donated the sources for the C/C++ modules. So I will not be able to proceed much further there.

I also had the task of replacing all the rest of the Java packages I need and use on Gentoo. So now I am like 99% free of Gentoos old broken outdated Java packages. Its been a fair amount of work if you see my activity. But its getting better. I need to [fix a bug](https://github.com/Obsidian-StudiosInc/jem/issues/2) in another C program jem, I used for Java Env Management. I will likely see about fixing this for entrance then.

Sorry for the delay, just juggling the world load...

**Comment by wltjr** [comment]
I restored the file and updated meson to install the file. It seems I never removed any code invoking that.  Just need to test now. If its good to go as is I will do another release. If not I can see about making further changes to fix. Just need to test build/install from git head/snapshot.

**Comment by wltjr** [comment]
Looks like I failed on the meson install portion.... I have to fix that and ensure its executable I believe.

**Comment by wltjr** [comment]
I failed with my packaging and testing, seems the meson was correct.

**Comment by wltjr** [comment]
File is in place, but seems to not be executed. Have to look into code and debug that aspect... Figures it does not work. I am pretty sure I did not remove any code there. I need to do a lot of work on entrance.

**Comment by wltjr** [comment]
Looks like it should be called/fired when ever consolekit is not in use. I assume I need consolekit for X but maybe not. Consolekit provides the ```XDG_SESSION_COOKIE``` session variable which I believe is needed. I was trying to find how to get the same for elogind if possible. Not sure if Xsession can be used with consolekit or not. It is presently coded for one or the other not both. Along same lines not sure if Xsession can be used with elogind.

**Comment by SolarAquarion** [comment]
https://www.freedesktop.org/software/systemd/man/pam_systemd.html there's
systemd variables

**Comment by wltjr** [comment]
Basically is the same as [pam_elogind](https://github.com/elogind/elogind) if you see the [man page(xml source)](https://github.com/elogind/elogind/blob/9826bd0b4642ce3699b5b8ff6503c6f2e1f3f3be/man/pam_elogind.xml#L70) It is the actual coding I am not sure about. I did not see any examples etc. I can likely figure it out. Not sure if I should keep [consolekit2](https://github.com/ConsoleKit2/ConsoleKit2) support or not in favor of elogind/systemd.

Not planning on full systemd support just the sessions stuff via logind/elogind. I assume pam_systemd is part of logind, or both parts of systemd package. At least I know it provides that session variable. Confirms it is needed. Not sure if things will work otherwise without consolekit or elogind/logind/systemd. I have to build and try to log in without consolekit2.

The longind build option is not really used other than to install the systemd service file. It doesn't build any code to support that yet.

**Comment by wltjr** [comment]
Did adding the Xsession file help you at all?

**Comment by SolarAquarion** [comment]
I  haven't tried yet, but let me try tomorrow

**Comment by SolarAquarion** [comment]
it doesn't launch for some reason

**Comment by wltjr** [comment]
I think I broke it with a recent commit, but that should just be consolekit2. But maybe also broken with the Xsession I need to test that out.

**Comment by wltjr** [comment]
Ok its better now. I still need to test out the Xsession but that should be fine. Providing that script is correct. I broke with a fix for a false double free for coverity due to odd code logic/flow. I just added another variable for coverity. Fixes the false double free, makes logic a bit better, and does not break usage.

**Comment by wltjr** [comment]
I tested out the Xsession file and something is missing it does not seem to set things up properly for E to start. I have to test further to see what its missing.

**Comment by wltjr** [comment]
Ok commits b1d24e1 9b5519c and 1131b82 should fix this issue. I am calling ```/etc/entrance/Xession``` before staring ```entrance_client``` and on login. That should resolve this issue. If you were wanting other Xesssion stuff setup as normal, xinitrc.d files processed etc.

If this is not, please let me know what you are unable to do or is not working. I may not be clear on the issue otherwise. Thank you!

**Comment by wltjr** [comment]
Duplicate of #16, with images and log output. Working that, will close this in favor of that one.
