### ISSUE TITLE
Should entrance really run as nobody?

### ISSUE THREAD

**Issue by TheTechRobo** [Obsidian-StudiosInc/entrance#51]
I've heard from multiple sources (https://serverfault.com/a/110335/590596, https://unix.stackexchange.com/a/186581/401349, and one other that I can't find anymore) that the `nobody` user with daemons should be avoided. Is there a reason that it was switched from user `entrance` to `nobody`?

**Comment by wltjr** [comment]
Hi, sorry for the delay. No, it should not run as nobody by default, but rather a entrance user, or some user created for entrance, or an existing account. I did not switch it from entrance to nobody, I believe, it was like that when I took over the code base. However, there is a configurable start_user in the entrance.conf file, which you can use to run entrance under a different user. I do it under travis user account in travis-ci.

I am fairly certain, it can be packaged and installed with a specific user account, instead of nobody. But nobody will be a fall back if that account does not exist. Thus, it is mostly a packaging issue, with the default being nobody, as that account is guaranteed to exist on all systems.

Creating an entrance user account would be something done as part of packaging and installing entrance, rather than something that would be handled by the build system. It could be configurable, but its just a setting in the conf file, so that is easily changed via sed, etc. It does not merit build system modifications for such.

**Comment by TheTechRobo** [comment]
Thanks for that detailed answer. :)

**Comment by wltjr** [comment]
Sure thing! Guess I will close this as there is nothing really to do at this time. If you find entrance does not work running under a user other than nobody, please open a new issue. Thank you!
